version: '3.9'

services:
   text-processor:
    container_name: text-processor
    image: python-text-processor
    networks:
      - ppd-project
    expose:
      - "1201"
    environment:
      - COUNTER_NUMBER=$COUNTER_NUMBER
    volumes:
      - ./text-processor/script:/script
   word-counter:
    image: python-word-counter
    networks:
      - ppd-project
    volumes:
      - ./counters/script:/script
    expose:
      - "1202"
    deploy:
      mode: replicated
      replicas: $COUNTER_NUMBER
    depends_on:
      - text-processor

networks:
  ppd-project:
    name: ppd-project
    driver: bridge